"General
:colorscheme desert
:set number
:set background=dark

"Kernel devel
:set tabstop=8
:set shiftwidth=8
:set softtabstop=8
:set noexpandtab

"Python devel
":set tabstop=4
":set shiftwidth=4
":set softtabstop=4
":set expandtab

